static COUNTRIES: std::sync::LazyLock<std::collections::HashMap<&'static str, &'static str>> =
    std::sync::LazyLock::new(|| {
        std::collections::HashMap::from([
            ("MN", "MN"),
            ("Mongolia", "MN"),
            ("PA", "PA"),
            ("Panama", "PA"),
            ("Republic of Panama", "PA"),
            ("República de Panamá", "PA"),
            ("Kingdom of Tonga", "TO"),
            ("TO", "TO"),
            ("Tonga", "TO"),
            ("Comoros", "KM"),
            ("KM", "KM"),
            ("Udzima wa Komori", "KM"),
            ("Union des Comores", "KM"),
            ("Union of the Comoros", "KM"),
            ("al-Ittiḥād al-Qumurī", "KM"),
            ("Kingdom of Sweden", "SE"),
            ("Konungariket Sverige", "SE"),
            ("SE", "SE"),
            ("Sweden", "SE"),
            ("GN", "GN"),
            ("Guinea", "GN"),
            ("Republic of Guinea", "GN"),
            ("République de Guinée", "GN"),
            ("FJ", "FJ"),
            ("Fiji", "FJ"),
            ("Fijī Gaṇarājya", "FJ"),
            ("Matanitu ko Viti", "FJ"),
            ("Republic of Fiji", "FJ"),
            ("Viti", "FJ"),
            ("Al-Mamlakah al-‘Arabiyyah as-Su‘ūdiyyah", "SA"),
            ("Kingdom of Saudi Arabia", "SA"),
            ("SA", "SA"),
            ("Saudi", "SA"),
            ("Saudi Arabia", "SA"),
            ("NC", "NC"),
            ("New Caledonia", "NC"),
            ("CV", "CV"),
            ("Cape Verde", "CV"),
            ("Republic of Cabo Verde", "CV"),
            ("República de Cabo Verde", "CV"),
            ("CX", "CX"),
            ("Christmas Island", "CX"),
            ("Territory of Christmas Island", "CX"),
            ("RSA", "ZA"),
            ("Republic of South Africa", "ZA"),
            ("South Africa", "ZA"),
            ("Suid-Afrika", "ZA"),
            ("ZA", "ZA"),
            ("IR", "IR"),
            ("Iran", "IR"),
            ("Iran, Islamic Republic of", "IR"),
            ("Islamic Republic of Iran", "IR"),
            ("Jomhuri-ye Eslāmi-ye Irān", "IR"),
            ("AZ", "AZ"),
            ("Azerbaijan", "AZ"),
            ("Azərbaycan Respublikası", "AZ"),
            ("Republic of Azerbaijan", "AZ"),
            ("Federal Democratic Republic of Nepal", "NP"),
            ("Loktāntrik Ganatantra Nepāl", "NP"),
            ("NP", "NP"),
            ("Nepal", "NP"),
            ("Al-Jumhūrīyah Al-Libnānīyah", "LB"),
            ("LB", "LB"),
            ("Lebanese Republic", "LB"),
            ("Lebanon", "LB"),
            ("British Indian Ocean Territory", "IO"),
            ("IO", "IO"),
            ("Republic of South Sudan", "SS"),
            ("SS", "SS"),
            ("South Sudan", "SS"),
            ("Democratic Republic of São Tomé and Príncipe", "ST"),
            ("República Democrática de São Tomé e Príncipe", "ST"),
            ("ST", "ST"),
            ("Sao Tome and Principe", "ST"),
            ("São Tomé and Príncipe", "ST"),
            ("MD", "MD"),
            ("Moldova", "MD"),
            ("Moldova, Republic of", "MD"),
            ("Republic of Moldova", "MD"),
            ("Republica Moldova", "MD"),
            ("United States Virgin Islands", "VI"),
            ("VI", "VI"),
            ("Virgin Islands of the United States", "VI"),
            ("Virgin Islands, U.S.", "VI"),
            ("RW", "RW"),
            ("Republic of Rwanda", "RW"),
            ("Repubulika y'u Rwanda", "RW"),
            ("Rwanda", "RW"),
            ("République du Rwanda", "RW"),
            ("Crna Gora", "ME"),
            ("ME", "ME"),
            ("Montenegro", "ME"),
            ("KG", "KG"),
            ("Kyrgyz Republic", "KG"),
            ("Kyrgyz Respublikasy", "KG"),
            ("Kyrgyzstan", "KG"),
            ("Киргизия", "KG"),
            ("Кыргыз Республикасы", "KG"),
            ("BI", "BI"),
            ("Burundi", "BI"),
            ("Republic of Burundi", "BI"),
            ("Republika y'Uburundi", "BI"),
            ("République du Burundi", "BI"),
            ("Independent and Sovereign Republic of Kiribati", "KI"),
            ("KI", "KI"),
            ("Kiribati", "KI"),
            ("Republic of Kiribati", "KI"),
            ("Ribaberiki Kiribati", "KI"),
            ("BB", "BB"),
            ("Barbados", "BB"),
            ("AD", "AD"),
            ("Andorra", "AD"),
            ("Principality of Andorra", "AD"),
            ("Principat d'Andorra", "AD"),
            ("KZ", "KZ"),
            ("Kazakhstan", "KZ"),
            ("Qazaqstan", "KZ"),
            ("Qazaqstan Respublïkası", "KZ"),
            ("Republic of Kazakhstan", "KZ"),
            ("Respublika Kazakhstan", "KZ"),
            ("Казахстан", "KZ"),
            ("Республика Казахстан", "KZ"),
            ("Қазақстан Республикасы", "KZ"),
            ("Hashemite Kingdom of Jordan", "JO"),
            ("JO", "JO"),
            ("Jordan", "JO"),
            ("al-Mamlakah al-Urdunīyah al-Hāshimīyah", "JO"),
            ("MO", "MO"),
            ("Macao", "MO"),
            (
                "Macao Special Administrative Region of the People's Republic of China",
                "MO",
            ),
            ("Macau", "MO"),
            (
                "Região Administrativa Especial de Macau da República Popular da China",
                "MO",
            ),
            ("中華人民共和國澳門特別行政區", "MO"),
            ("澳门", "MO"),
            ("CY", "CY"),
            ("Cyprus", "CY"),
            ("Kýpros", "CY"),
            ("Kıbrıs", "CY"),
            ("Kıbrıs Cumhuriyeti", "CY"),
            ("Republic of Cyprus", "CY"),
            ("Κυπριακή Δημοκρατία", "CY"),
            ("ID", "ID"),
            ("Indonesia", "ID"),
            ("Republic of Indonesia", "ID"),
            ("Republik Indonesia", "ID"),
            ("El Salvador", "SV"),
            ("Republic of El Salvador", "SV"),
            ("República de El Salvador", "SV"),
            ("SV", "SV"),
            ("AX", "AX"),
            ("Aaland", "AX"),
            ("Ahvenanmaa", "AX"),
            ("Aland", "AX"),
            ("Åland Islands", "AX"),
            ("BN", "BN"),
            ("Brunei", "BN"),
            ("Brunei Darussalam", "BN"),
            ("Nation of Brunei", "BN"),
            ("Nation of Brunei, Abode of Peace", "BN"),
            ("the Abode of Peace", "BN"),
            ("Territoire des îles Wallis et Futuna", "WF"),
            ("Territory of the Wallis and Futuna Islands", "WF"),
            ("WF", "WF"),
            ("Wallis and Futuna", "WF"),
            ("JP", "JP"),
            ("Japan", "JP"),
            ("Nihon", "JP"),
            ("Nippon", "JP"),
            ("EE", "EE"),
            ("Eesti", "EE"),
            ("Eesti Vabariik", "EE"),
            ("Estonia", "EE"),
            ("Republic of Estonia", "EE"),
            ("Commonwealth of the Northern Mariana Islands", "MP"),
            ("MP", "MP"),
            ("Northern Mariana Islands", "MP"),
            ("Sankattan Siha Na Islas Mariånas", "MP"),
            ("CA", "CA"),
            ("Canada", "CA"),
            ("French Southern Territories", "TF"),
            ("French Southern and Antarctic Lands", "TF"),
            ("TF", "TF"),
            ("Territory of the French Southern and Antarctic Lands", "TF"),
            ("SJ", "SJ"),
            ("Svalbard and Jan Mayen", "SJ"),
            ("Svalbard and Jan Mayen Islands", "SJ"),
            ("Svalbard og Jan Mayen", "SJ"),
            ("AE", "AE"),
            ("Emirates", "AE"),
            ("UAE", "AE"),
            ("United Arab Emirates", "AE"),
            ("BW", "BW"),
            ("Botswana", "BW"),
            ("Lefatshe la Botswana", "BW"),
            ("Republic of Botswana", "BW"),
            ("Islamic Republic of Mauritania", "MR"),
            ("MR", "MR"),
            ("Mauritania", "MR"),
            ("al-Jumhūriyyah al-ʾIslāmiyyah al-Mūrītāniyyah", "MR"),
            ("EH", "EH"),
            ("Sahrawi Arab Democratic Republic", "EH"),
            ("Taneẓroft Tutrimt", "EH"),
            ("Western Sahara", "EH"),
            ("GU", "GU"),
            ("Guam", "GU"),
            ("Guåhån", "GU"),
            ("MG", "MG"),
            ("Madagascar", "MG"),
            ("Repoblikan'i Madagasikara", "MG"),
            ("Republic of Madagascar", "MG"),
            ("République de Madagascar", "MG"),
            ("LA", "LA"),
            ("Lao", "LA"),
            ("Lao People's Democratic Republic", "LA"),
            ("Laos", "LA"),
            ("Sathalanalat Paxathipatai Paxaxon Lao", "LA"),
            ("Federal Republic of Somalia", "SO"),
            ("Jamhuuriyadda Federaalka Soomaaliya", "SO"),
            ("Jumhūriyyat aṣ-Ṣūmāl al-Fiderāliyya", "SO"),
            ("SO", "SO"),
            ("Somalia", "SO"),
            ("aṣ-Ṣūmāl", "SO"),
            ("HT", "HT"),
            ("Haiti", "HT"),
            ("Repiblik Ayiti", "HT"),
            ("Republic of Haiti", "HT"),
            ("République d'Haïti", "HT"),
            ("FK", "FK"),
            ("Falkland Islands", "FK"),
            ("Falkland Islands (Malvinas)", "FK"),
            ("Islas Malvinas", "FK"),
            ("CZ", "CZ"),
            ("Czech Republic", "CZ"),
            ("Czechia", "CZ"),
            ("Česko", "CZ"),
            ("Česká republika", "CZ"),
            ("BS", "BS"),
            ("Bahamas", "BS"),
            ("Commonwealth of the Bahamas", "BS"),
            ("MT", "MT"),
            ("Malta", "MT"),
            ("Repubblika ta' Malta", "MT"),
            ("Republic of Malta", "MT"),
            ("MU", "MU"),
            ("Mauritius", "MU"),
            ("Republic of Mauritius", "MU"),
            ("République de Maurice", "MU"),
            ("Islamic Republic of Pakistan", "PK"),
            ("Islāmī Jumhūriya'eh Pākistān", "PK"),
            ("PK", "PK"),
            ("Pakistan", "PK"),
            ("Pākistān", "PK"),
            ("Jumhūrīyat as-Sūdān", "SD"),
            ("Republic of the Sudan", "SD"),
            ("SD", "SD"),
            ("Sudan", "SD"),
            ("LV", "LV"),
            ("Latvia", "LV"),
            ("Latvijas Republika", "LV"),
            ("Republic of Latvia", "LV"),
            ("LT", "LT"),
            ("Lietuvos Respublika", "LT"),
            ("Lithuania", "LT"),
            ("Republic of Lithuania", "LT"),
            ("PT", "PT"),
            ("Portugal", "PT"),
            ("Portuguesa", "PT"),
            ("Portuguese Republic", "PT"),
            ("República Portuguesa", "PT"),
            ("Grand Duchy of Luxembourg", "LU"),
            ("Grand-Duché de Luxembourg", "LU"),
            ("Groussherzogtum Lëtzebuerg", "LU"),
            ("Großherzogtum Luxemburg", "LU"),
            ("LU", "LU"),
            ("Luxembourg", "LU"),
            ("MK", "MK"),
            ("Macedonia, The Former Yugoslav Republic of", "MK"),
            ("North Macedonia", "MK"),
            ("Republic of North Macedonia", "MK"),
            ("The former Yugoslav Republic of Macedonia", "MK"),
            ("Република Северна Македонија", "MK"),
            ("GS", "GS"),
            ("South Georgia", "GS"),
            ("South Georgia and the South Sandwich Islands", "GS"),
            ("RS", "RS"),
            ("Republic of Serbia", "RS"),
            ("Republika Srbija", "RS"),
            ("Serbia", "RS"),
            ("Srbija", "RS"),
            ("Република Србија", "RS"),
            ("GB", "GB"),
            ("Great Britain", "GB"),
            ("UK", "GB"),
            ("United Kingdom", "GB"),
            ("United Kingdom of Great Britain and Northern Ireland", "GB"),
            ("TK", "TK"),
            ("Tokelau", "TK"),
            ("Jamhuri ya Kenya", "KE"),
            ("KE", "KE"),
            ("Kenya", "KE"),
            ("Republic of Kenya", "KE"),
            ("NE", "NE"),
            ("Niger", "NE"),
            ("Nijar", "NE"),
            ("Republic of Niger", "NE"),
            ("CG", "CG"),
            ("Congo", "CG"),
            ("Congo-Brazzaville", "CG"),
            ("Republic of the Congo", "CG"),
            ("CU", "CU"),
            ("Cuba", "CU"),
            ("Republic of Cuba", "CU"),
            ("República de Cuba", "CU"),
            ("Eswatini", "SZ"),
            ("Kingdom of Eswatini", "SZ"),
            ("Ngwane", "SZ"),
            ("SZ", "SZ"),
            ("Swatini", "SZ"),
            ("Swaziland", "SZ"),
            ("Umbuso weSwatini", "SZ"),
            ("weSwatini", "SZ"),
            ("AL", "AL"),
            ("Albania", "AL"),
            ("Republic of Albania", "AL"),
            ("Shqipnia", "AL"),
            ("Shqipëri", "AL"),
            ("Shqipëria", "AL"),
            ("ML", "ML"),
            ("Mali", "ML"),
            ("Republic of Mali", "ML"),
            ("République du Mali", "ML"),
            ("République Togolaise", "TG"),
            ("TG", "TG"),
            ("Togo", "TG"),
            ("Togolese", "TG"),
            ("Togolese Republic", "TG"),
            ("RO", "RO"),
            ("Romania", "RO"),
            ("România", "RO"),
            ("Roumania", "RO"),
            ("Rumania", "RO"),
            ("OM", "OM"),
            ("Oman", "OM"),
            ("Salṭanat ʻUmān", "OM"),
            ("Sultanate of Oman", "OM"),
            ("Arab Republic of Egypt", "EG"),
            ("EG", "EG"),
            ("Egypt", "EG"),
            ("Aotearoa", "NZ"),
            ("NZ", "NZ"),
            ("New Zealand", "NZ"),
            ("RU", "RU"),
            ("Russia", "RU"),
            ("Russian Federation", "RU"),
            ("Российская Федерация", "RU"),
            ("TM", "TM"),
            ("Turkmenistan", "TM"),
            ("CM", "CM"),
            ("Cameroon", "CM"),
            ("Republic of Cameroon", "CM"),
            ("République du Cameroun", "CM"),
            ("CK", "CK"),
            ("Cook Islands", "CK"),
            ("Kūki 'Āirani", "CK"),
            ("Republic of Slovenia", "SI"),
            ("Republika Slovenija", "SI"),
            ("SI", "SI"),
            ("Slovenia", "SI"),
            ("Republic of Vanuatu", "VU"),
            ("Ripablik blong Vanuatu", "VU"),
            ("République de Vanuatu", "VU"),
            ("VU", "VU"),
            ("Vanuatu", "VU"),
            ("Federation of Saint Christopher and Nevis", "KN"),
            ("KN", "KN"),
            ("Saint Kitts and Nevis", "KN"),
            ("Oriental Republic of Uruguay", "UY"),
            ("República Oriental del Uruguay", "UY"),
            ("UY", "UY"),
            ("Uruguay", "UY"),
            ("DK", "DK"),
            ("Danmark", "DK"),
            ("Denmark", "DK"),
            ("Kingdom of Denmark", "DK"),
            ("Kongeriget Danmark", "DK"),
            ("PH", "PH"),
            ("Philippines", "PH"),
            ("Republic of the Philippines", "PH"),
            ("Repúblika ng Pilipinas", "PH"),
            ("Dawlat Filasṭin", "PS"),
            ("PS", "PS"),
            ("Palestine", "PS"),
            ("Palestine, State of", "PS"),
            ("State of Palestine", "PS"),
            ("PN", "PN"),
            ("Pitcairn", "PN"),
            ("Pitcairn Group of Islands", "PN"),
            ("Pitcairn Henderson Ducie and Oeno Islands", "PN"),
            ("Pitcairn Islands", "PN"),
            ("French Guiana", "GF"),
            ("GF", "GF"),
            ("Guiana", "GF"),
            ("Guyane", "GF"),
            ("IT", "IT"),
            ("Italian Republic", "IT"),
            ("Italy", "IT"),
            ("Repubblica italiana", "IT"),
            ("O‘zbekiston Respublikasi", "UZ"),
            ("Republic of Uzbekistan", "UZ"),
            ("UZ", "UZ"),
            ("Uzbekistan", "UZ"),
            ("Ўзбекистон Республикаси", "UZ"),
            ("Commonwealth of Dominica", "DM"),
            ("DM", "DM"),
            ("Dominica", "DM"),
            ("Dominique", "DM"),
            ("Wai‘tu kubuli", "DM"),
            ("FI", "FI"),
            ("Finland", "FI"),
            ("Republic of Finland", "FI"),
            ("Republiken Finland", "FI"),
            ("Suomen tasavalta", "FI"),
            ("Suomi", "FI"),
            ("KR", "KR"),
            ("Korea, Republic of", "KR"),
            ("Republic of Korea", "KR"),
            ("South Korea", "KR"),
            ("남조선", "KR"),
            ("남한", "KR"),
            ("HM", "HM"),
            ("Heard Island and McDonald Islands", "HM"),
            ("FO", "FO"),
            ("Faroe Islands", "FO"),
            ("Færøerne", "FO"),
            ("Føroyar", "FO"),
            ("Dawlat Qaṭar", "QA"),
            ("QA", "QA"),
            ("Qatar", "QA"),
            ("State of Qatar", "QA"),
            ("Bharat Ganrajya", "IN"),
            ("Bhārat", "IN"),
            ("IN", "IN"),
            ("India", "IN"),
            ("Republic of India", "IN"),
            ("இந்தியா", "IN"),
            ("Department of Mayotte", "YT"),
            ("Département de Mayotte", "YT"),
            ("Mayotte", "YT"),
            ("YT", "YT"),
            ("GP", "GP"),
            ("Guadeloupe", "GP"),
            ("Gwadloup", "GP"),
            ("MZ", "MZ"),
            ("Mozambique", "MZ"),
            ("Republic of Mozambique", "MZ"),
            ("República de Moçambique", "MZ"),
            ("BV", "BV"),
            ("Bouvet Island", "BV"),
            ("Bouvet-øya", "BV"),
            ("Bouvetøya", "BV"),
            ("Republic of Yemen", "YE"),
            ("YE", "YE"),
            ("Yemen", "YE"),
            ("Yemeni Republic", "YE"),
            ("al-Jumhūriyyah al-Yamaniyyah", "YE"),
            ("Kosovo", "XK"),
            ("Republic of Kosovo", "XK"),
            ("XK", "XK"),
            ("Република Косово", "XK"),
            ("Chinese Taipei", "TW"),
            ("Republic of China", "TW"),
            ("Republic of China (Taiwan)", "TW"),
            ("TW", "TW"),
            ("Taiwan", "TW"),
            ("Táiwān", "TW"),
            ("Zhōnghuá Mínguó", "TW"),
            ("中華民國", "TW"),
            ("BM", "BM"),
            ("Bermuda", "BM"),
            ("Somers Isles", "BM"),
            ("The Bermudas", "BM"),
            ("The Islands of Bermuda", "BM"),
            ("GE", "GE"),
            ("Georgia", "GE"),
            ("Sakartvelo", "GE"),
            ("AI", "AI"),
            ("Anguilla", "AI"),
            ("Saint Vincent and the Grenadines", "VC"),
            ("VC", "VC"),
            ("BZ", "BZ"),
            ("Belize", "BZ"),
            ("MW", "MW"),
            ("Malawi", "MW"),
            ("Republic of Malawi", "MW"),
            ("AW", "AW"),
            ("Aruba", "AW"),
            ("IL", "IL"),
            ("Israel", "IL"),
            ("Medīnat Yisrā'el", "IL"),
            ("State of Israel", "IL"),
            ("Ellan Vannin", "IM"),
            ("IM", "IM"),
            ("Isle of Man", "IM"),
            ("Mann", "IM"),
            ("Mannin", "IM"),
            ("BY", "BY"),
            ("Belarus", "BY"),
            ("Bielaruś", "BY"),
            ("Republic of Belarus", "BY"),
            ("Белоруссия", "BY"),
            ("Республика Белоруссия", "BY"),
            ("NA", "NA"),
            ("Namibia", "NA"),
            ("Namibië", "NA"),
            ("Republic of Namibia", "NA"),
            ("GT", "GT"),
            ("Guatemala", "GT"),
            ("Republic of Guatemala", "GT"),
            ("BR", "BR"),
            ("Brasil", "BR"),
            ("Brazil", "BR"),
            ("Federative Republic of Brazil", "BR"),
            ("República Federativa do Brasil", "BR"),
            ("PL", "PL"),
            ("Poland", "PL"),
            ("Republic of Poland", "PL"),
            ("Rzeczpospolita Polska", "PL"),
            ("Dhivehi Raajjeyge Jumhooriyya", "MV"),
            ("MV", "MV"),
            ("Maldive Islands", "MV"),
            ("Maldives", "MV"),
            ("Republic of the Maldives", "MV"),
            ("Republic of Singapore", "SG"),
            ("Republik Singapura", "SG"),
            ("SG", "SG"),
            ("Singapore", "SG"),
            ("Singapura", "SG"),
            ("新加坡共和国", "SG"),
            ("GL", "GL"),
            ("Greenland", "GL"),
            ("Grønland", "GL"),
            ("Co-operative Republic of Guyana", "GY"),
            ("GY", "GY"),
            ("Guyana", "GY"),
            ("Chosŏn Minjujuŭi Inmin Konghwaguk", "KP"),
            ("DPRK", "KP"),
            ("Democratic People's Republic of Korea", "KP"),
            ("KP", "KP"),
            ("Korea, Democratic People's Republic of", "KP"),
            ("North Korea", "KP"),
            ("북조선", "KP"),
            ("북한", "KP"),
            ("조선민주주의인민공화국", "KP"),
            ("IE", "IE"),
            ("Ireland", "IE"),
            ("Poblacht na hÉireann", "IE"),
            ("Republic of Ireland", "IE"),
            ("Éire", "IE"),
            ("SB", "SB"),
            ("Solomon Islands", "SB"),
            ("GI", "GI"),
            ("Gibraltar", "GI"),
            ("Aolepān Aorōkin M̧ajeļ", "MH"),
            ("MH", "MH"),
            ("Marshall Islands", "MH"),
            ("Republic of the Marshall Islands", "MH"),
            ("Republic of Tunisia", "TN"),
            ("TN", "TN"),
            ("Tunisia", "TN"),
            ("Tunisian Republic", "TN"),
            ("al-Jumhūriyyah at-Tūnisiyyah", "TN"),
            ("TV", "TV"),
            ("Tuvalu", "TV"),
            ("SX", "SX"),
            ("Sint Maarten", "SX"),
            ("Sint Maarten (Dutch part)", "SX"),
            ("Dawlat Iritriyá", "ER"),
            ("ER", "ER"),
            ("Eritrea", "ER"),
            ("Iritriyā", "ER"),
            ("State of Eritrea", "ER"),
            ("ʾErtrā", "ER"),
            ("ሃገረ ኤርትራ", "ER"),
            ("Independent State of Samoa", "WS"),
            ("Malo Saʻoloto Tutoʻatasi o Sāmoa", "WS"),
            ("Samoa", "WS"),
            ("WS", "WS"),
            ("DO", "DO"),
            ("Dominican Republic", "DO"),
            ("Jamhuri ya Uganda", "UG"),
            ("Republic of Uganda", "UG"),
            ("UG", "UG"),
            ("Uganda", "UG"),
            ("IQ", "IQ"),
            ("Iraq", "IQ"),
            ("Jumhūriyyat al-‘Irāq", "IQ"),
            ("Republic of Iraq", "IQ"),
            ("UA", "UA"),
            ("Ukraine", "UA"),
            ("Ukrayina", "UA"),
            ("LR", "LR"),
            ("Liberia", "LR"),
            ("Republic of Liberia", "LR"),
            ("HK", "HK"),
            ("Hong Kong", "HK"),
            (
                "Hong Kong Special Administrative Region of the People's Republic of China",
                "HK",
            ),
            ("NR", "NR"),
            ("Naoero", "NR"),
            ("Nauru", "NR"),
            ("Pleasant Island", "NR"),
            ("Republic of Nauru", "NR"),
            ("Ripublik Naoero", "NR"),
            ("Fürstentum Liechtenstein", "LI"),
            ("LI", "LI"),
            ("Liechtenstein", "LI"),
            ("Principality of Liechtenstein", "LI"),
            ("ES", "ES"),
            ("Kingdom of Spain", "ES"),
            ("Reino de España", "ES"),
            ("Spain", "ES"),
            ("Republic of Turkey", "TR"),
            ("TR", "TR"),
            ("Turkey", "TR"),
            ("Turkiye", "TR"),
            ("Türkiye Cumhuriyeti", "TR"),
            ("UM", "UM"),
            ("United States Minor Outlying Islands", "UM"),
            ("Bundesrepublik Deutschland", "DE"),
            ("DE", "DE"),
            ("Federal Republic of Germany", "DE"),
            ("Germany", "DE"),
            ("Repiblik Sesel", "SC"),
            ("Republic of Seychelles", "SC"),
            ("République des Seychelles", "SC"),
            ("SC", "SC"),
            ("Seychelles", "SC"),
            ("AU", "AU"),
            ("Australia", "AU"),
            ("Commonwealth of Australia", "AU"),
            ("BG", "BG"),
            ("Bulgaria", "BG"),
            ("Republic of Bulgaria", "BG"),
            ("Република България", "BG"),
            ("Algeria", "DZ"),
            ("Algérie", "DZ"),
            ("DZ", "DZ"),
            ("Dzayer", "DZ"),
            ("People's Democratic Republic of Algeria", "DZ"),
            ("AO", "AO"),
            ("Angola", "AO"),
            ("Republic of Angola", "AO"),
            ("República de Angola", "AO"),
            ("ʁɛpublika de an'ɡɔla", "AO"),
            ("PE", "PE"),
            ("Peru", "PE"),
            ("Republic of Peru", "PE"),
            ("República del Perú", "PE"),
            ("CL", "CL"),
            ("Chile", "CL"),
            ("Republic of Chile", "CL"),
            ("República de Chile", "CL"),
            ("NI", "NI"),
            ("Nicaragua", "NI"),
            ("Republic of Nicaragua", "NI"),
            ("República de Nicaragua", "NI"),
            ("Republic of Zimbabwe", "ZW"),
            ("ZW", "ZW"),
            ("Zimbabwe", "ZW"),
            ("Bailiwick of Jersey", "JE"),
            ("Bailliage de Jersey", "JE"),
            ("Bailliage dé Jèrri", "JE"),
            ("JE", "JE"),
            ("Jersey", "JE"),
            ("BJ", "BJ"),
            ("Benin", "BJ"),
            ("Republic of Benin", "BJ"),
            ("République du Bénin", "BJ"),
            ("CO", "CO"),
            ("Colombia", "CO"),
            ("Republic of Colombia", "CO"),
            ("República de Colombia", "CO"),
            ("AT", "AT"),
            ("Austria", "AT"),
            ("Oesterreich", "AT"),
            ("Osterreich", "AT"),
            ("Republic of Austria", "AT"),
            ("BH", "BH"),
            ("Bahrain", "BH"),
            ("Kingdom of Bahrain", "BH"),
            ("Mamlakat al-Baḥrayn", "BH"),
            ("Al-Mamlakah al-Maġribiyah", "MA"),
            ("Kingdom of Morocco", "MA"),
            ("MA", "MA"),
            ("Morocco", "MA"),
            ("Jamhuri ya Muungano wa Tanzania", "TZ"),
            ("TZ", "TZ"),
            ("Tanzania", "TZ"),
            ("Tanzania, United Republic of", "TZ"),
            ("United Republic of Tanzania", "TZ"),
            ("GD", "GD"),
            ("Grenada", "GD"),
            ("British Virgin Islands", "VG"),
            ("VG", "VG"),
            ("Virgin Islands", "VG"),
            ("Virgin Islands, British", "VG"),
            ("Repubblica di San Marino", "SM"),
            ("Republic of San Marino", "SM"),
            ("SM", "SM"),
            ("San Marino", "SM"),
            ("Bolivarian Republic of Venezuela", "VE"),
            ("República Bolivariana de Venezuela", "VE"),
            ("VE", "VE"),
            ("Venezuela", "VE"),
            ("Venezuela, Bolivarian Republic of", "VE"),
            ("GW", "GW"),
            ("Guinea-Bissau", "GW"),
            ("Republic of Guinea-Bissau", "GW"),
            ("República da Guiné-Bissau", "GW"),
            ("NF", "NF"),
            ("Norfolk Island", "NF"),
            ("Teratri of Norf'k Ailen", "NF"),
            ("Territory of Norfolk Island", "NF"),
            ("IS", "IS"),
            ("Iceland", "IS"),
            ("Island", "IS"),
            ("Lýðveldið Ísland", "IS"),
            ("Republic of Iceland", "IS"),
            ("MS", "MS"),
            ("Montserrat", "MS"),
            ("US", "US"),
            ("USA", "US"),
            ("United States", "US"),
            ("United States of America", "US"),
            ("Republic of Trinidad and Tobago", "TT"),
            ("TT", "TT"),
            ("Trinidad and Tobago", "TT"),
            ("FR", "FR"),
            ("France", "FR"),
            ("French Republic", "FR"),
            ("République française", "FR"),
            ("MQ", "MQ"),
            ("Martinique", "MQ"),
            ("CR", "CR"),
            ("Costa Rica", "CR"),
            ("Republic of Costa Rica", "CR"),
            ("República de Costa Rica", "CR"),
            ("BE", "BE"),
            ("Belgie", "BE"),
            ("Belgien", "BE"),
            ("Belgique", "BE"),
            ("Belgium", "BE"),
            ("België", "BE"),
            ("Kingdom of Belgium", "BE"),
            ("Koninkrijk België", "BE"),
            ("Königreich Belgien", "BE"),
            ("Royaume de Belgique", "BE"),
            ("Collectivity of Saint Martin", "MF"),
            ("Collectivité de Saint-Martin", "MF"),
            ("MF", "MF"),
            ("Saint Martin", "MF"),
            ("Saint Martin (French part)", "MF"),
            ("Independen Stet bilong Papua Niugini", "PG"),
            ("Independent State of Papua New Guinea", "PG"),
            ("PG", "PG"),
            ("Papua New Guinea", "PG"),
            ("FM", "FM"),
            ("Federated States of Micronesia", "FM"),
            ("Micronesia", "FM"),
            ("Micronesia, Federated States of", "FM"),
            ("AG", "AG"),
            ("Antigua and Barbuda", "AG"),
            ("Cambodia", "KH"),
            ("KH", "KH"),
            ("Kingdom of Cambodia", "KH"),
            ("JM", "JM"),
            ("Jamaica", "JM"),
            ("Republic of Suriname", "SR"),
            ("Republiek Suriname", "SR"),
            ("SR", "SR"),
            ("Sarnam", "SR"),
            ("Sranangron", "SR"),
            ("Suriname", "SR"),
            ("Republic of Zambia", "ZM"),
            ("ZM", "ZM"),
            ("Zambia", "ZM"),
            ("AM", "AM"),
            ("Armenia", "AM"),
            ("Hayastan", "AM"),
            ("Republic of Armenia", "AM"),
            ("Հայաստանի Հանրապետություն", "AM"),
            ("TC", "TC"),
            ("Turks and Caicos Islands", "TC"),
            ("GA", "GA"),
            ("Gabon", "GA"),
            ("Gabonese Republic", "GA"),
            ("République Gabonaise", "GA"),
            ("Cộng hòa Xã hội chủ nghĩa Việt Nam", "VN"),
            ("Socialist Republic of Vietnam", "VN"),
            ("VN", "VN"),
            ("Viet Nam", "VN"),
            ("Vietnam", "VN"),
            ("DJ", "DJ"),
            ("Djibouti", "DJ"),
            ("Gabuuti", "DJ"),
            ("Gabuutih Ummuuno", "DJ"),
            ("Jabuuti", "DJ"),
            ("Jamhuuriyadda Jabuuti", "DJ"),
            ("Republic of Djibouti", "DJ"),
            ("République de Djibouti", "DJ"),
            ("Bailiwick of Guernsey", "GG"),
            ("Bailliage de Guernesey", "GG"),
            ("GG", "GG"),
            ("Guernsey", "GG"),
            ("Saint Helena", "SH"),
            ("Saint Helena, Ascension and Tristan da Cunha", "SH"),
            ("St. Helena, Ascension and Tristan da Cunha", "SH"),
            ("Elláda", "GR"),
            ("GR", "GR"),
            ("Greece", "GR"),
            ("Hellenic Republic", "GR"),
            ("Ελληνική Δημοκρατία", "GR"),
            ("French Polynesia", "PF"),
            ("PF", "PF"),
            ("Polynésie française", "PF"),
            ("Pōrīnetia Farāni", "PF"),
            ("Dawlat al-Kuwait", "KW"),
            ("KW", "KW"),
            ("Kuwait", "KW"),
            ("State of Kuwait", "KW"),
            ("Republic of Sierra Leone", "SL"),
            ("SL", "SL"),
            ("Sierra Leone", "SL"),
            ("AQ", "AQ"),
            ("Antarctica", "AQ"),
            ("HN", "HN"),
            ("Honduras", "HN"),
            ("Republic of Honduras", "HN"),
            ("República de Honduras", "HN"),
            ("Estados Unidos Mexicanos", "MX"),
            ("MX", "MX"),
            ("Mexicanos", "MX"),
            ("Mexico", "MX"),
            ("United Mexican States", "MX"),
            ("Federal Republic of Nigeria", "NG"),
            ("NG", "NG"),
            ("Naíjíríà", "NG"),
            ("Nigeria", "NG"),
            ("Nijeriya", "NG"),
            ("Dawlat Libya", "LY"),
            ("LY", "LY"),
            ("Libya", "LY"),
            ("State of Libya", "LY"),
            ("Kingdom of Thailand", "TH"),
            ("Prathet", "TH"),
            ("Ratcha Anachak Thai", "TH"),
            ("TH", "TH"),
            ("Thai", "TH"),
            ("Thailand", "TH"),
            ("ราชอาณาจักรไทย", "TH"),
            ("CF", "CF"),
            ("Central African Republic", "CF"),
            ("République centrafricaine", "CF"),
            ("PY", "PY"),
            ("Paraguay", "PY"),
            ("Republic of Paraguay", "PY"),
            ("República del Paraguay", "PY"),
            ("Tetã Paraguái", "PY"),
            ("Democratic Republic of Timor-Leste", "TL"),
            ("East Timor", "TL"),
            ("República Democrática de Timor-Leste", "TL"),
            ("Repúblika Demokrátika Timór-Leste", "TL"),
            ("TL", "TL"),
            ("Timor Lorosae", "TL"),
            ("Timor-Leste", "TL"),
            ("Timór Lorosa'e", "TL"),
            ("AS", "AS"),
            ("Amelika Sāmoa", "AS"),
            ("American Samoa", "AS"),
            ("Amerika Sāmoa", "AS"),
            ("Sāmoa Amelika", "AS"),
            ("Republic of Senegal", "SN"),
            ("République du Sénégal", "SN"),
            ("SN", "SN"),
            ("Senegal", "SN"),
            ("RE", "RE"),
            ("Reunion", "RE"),
            ("Réunion", "RE"),
            ("Réunion Island", "RE"),
            ("LC", "LC"),
            ("Saint Lucia", "LC"),
            ("AF", "AF"),
            ("Afghanistan", "AF"),
            ("Afġānistān", "AF"),
            ("Islamic Republic of Afghanistan", "AF"),
            ("BT", "BT"),
            ("Bhutan", "BT"),
            ("Kingdom of Bhutan", "BT"),
            ("Burma", "MM"),
            ("MM", "MM"),
            ("Myanmar", "MM"),
            ("Pyidaunzu Thanmăda Myăma Nainngandaw", "MM"),
            ("Republic of the Union of Myanmar", "MM"),
            ("Equatorial Guinea", "GQ"),
            ("GQ", "GQ"),
            ("Republic of Equatorial Guinea", "GQ"),
            ("República da Guiné Equatorial", "GQ"),
            ("República de Guinea Ecuatorial", "GQ"),
            ("République de Guinée équatoriale", "GQ"),
            ("CC", "CC"),
            ("Cocos (Keeling) Islands", "CC"),
            ("Cocos Islands", "CC"),
            ("Keeling Islands", "CC"),
            ("Territory of the Cocos (Keeling) Islands", "CC"),
            ("Al-Jumhūrīyah Al-ʻArabīyah As-Sūrīyah", "SY"),
            ("SY", "SY"),
            ("Syria", "SY"),
            ("Syrian Arab Republic", "SY"),
            ("Croatia", "HR"),
            ("HR", "HR"),
            ("Hrvatska", "HR"),
            ("Republic of Croatia", "HR"),
            ("Republika Hrvatska", "HR"),
            ("Commonwealth of Puerto Rico", "PR"),
            ("Estado Libre Asociado de Puerto Rico", "PR"),
            ("PR", "PR"),
            ("Puerto Rico", "PR"),
            ("BES islands", "BQ"),
            ("Bonaire, Sint Eustatius and Saba", "BQ"),
            ("Caribbean Netherlands", "BQ"),
            ("BO", "BO"),
            ("Bolivia", "BO"),
            ("Bolivia, Plurinational State of", "BO"),
            ("Buliwya", "BO"),
            ("Buliwya Mamallaqta", "BO"),
            ("Estado Plurinacional de Bolivia", "BO"),
            ("Plurinational State of Bolivia", "BO"),
            ("Tetã Volívia", "BO"),
            ("Wuliwya", "BO"),
            ("Wuliwya Suyu", "BO"),
            (
                "Collectivité territoriale de Saint-Pierre-et-Miquelon",
                "PM",
            ),
            ("PM", "PM"),
            ("Saint Pierre and Miquelon", "PM"),
            ("CD", "CD"),
            ("Congo, the Democratic Republic of the", "CD"),
            ("Congo-Kinshasa", "CD"),
            ("DR Congo", "CD"),
            ("DRC", "CD"),
            ("Democratic Republic of the Congo", "CD"),
            ("AR", "AR"),
            ("Argentina", "AR"),
            ("Argentine Republic", "AR"),
            ("República Argentina", "AR"),
            ("Democratic Socialist Republic of Sri Lanka", "LK"),
            ("LK", "LK"),
            ("Sri Lanka", "LK"),
            ("ilaṅkai", "LK"),
            ("Chad", "TD"),
            ("Republic of Chad", "TD"),
            ("République du Tchad", "TD"),
            ("TD", "TD"),
            ("Tchad", "TD"),
            ("CW", "CW"),
            ("Country of Curaçao", "CW"),
            ("Curacao", "CW"),
            ("Curaçao", "CW"),
            ("Kòrsou", "CW"),
            ("Land Curaçao", "CW"),
            ("Pais Kòrsou", "CW"),
            ("EC", "EC"),
            ("Ecuador", "EC"),
            ("Republic of Ecuador", "EC"),
            ("República del Ecuador", "EC"),
            ("Kingdom of Lesotho", "LS"),
            ("LS", "LS"),
            ("Lesotho", "LS"),
            ("Muso oa Lesotho", "LS"),
            ("GM", "GM"),
            ("Gambia", "GM"),
            ("Republic of the Gambia", "GM"),
            ("SK", "SK"),
            ("Slovak Republic", "SK"),
            ("Slovakia", "SK"),
            ("Slovenská republika", "SK"),
            ("MY", "MY"),
            ("Malaysia", "MY"),
            ("Kingdom of Norway", "NO"),
            ("Kongeriket Noreg", "NO"),
            ("Kongeriket Norge", "NO"),
            ("NO", "NO"),
            ("Noreg", "NO"),
            ("Norge", "NO"),
            ("Norway", "NO"),
            ("GH", "GH"),
            ("Ghana", "GH"),
            ("Republic of Ghana", "GH"),
            ("CH", "CH"),
            ("Schweiz", "CH"),
            ("Suisse", "CH"),
            ("Svizra", "CH"),
            ("Svizzera", "CH"),
            ("Swiss Confederation", "CH"),
            ("Switzerland", "CH"),
            ("HU", "HU"),
            ("Hungary", "HU"),
            ("Holy See (Vatican City State)", "VA"),
            ("Stato della Città del Vaticano", "VA"),
            ("VA", "VA"),
            ("Vatican City", "VA"),
            ("Vatican City State", "VA"),
            ("Holland", "NL"),
            ("Kingdom of the Netherlands", "NL"),
            ("NL", "NL"),
            ("Nederland", "NL"),
            ("Netherlands", "NL"),
            ("The Netherlands", "NL"),
            ("BF", "BF"),
            ("Burkina Faso", "BF"),
            ("BD", "BD"),
            ("Bangladesh", "BD"),
            ("Gônôprôjatôntri Bangladesh", "BD"),
            ("People's Republic of Bangladesh", "BD"),
            ("NU", "NU"),
            ("Niue", "NU"),
            ("CI", "CI"),
            ("Côte d'Ivoire", "CI"),
            ("Ivory Coast", "CI"),
            ("Republic of Côte d'Ivoire", "CI"),
            ("République de Côte d'Ivoire", "CI"),
            ("MC", "MC"),
            ("Monaco", "MC"),
            ("Principality of Monaco", "MC"),
            ("Principauté de Monaco", "MC"),
            ("Cayman Islands", "KY"),
            ("KY", "KY"),
            ("ET", "ET"),
            ("Ethiopia", "ET"),
            ("Federal Democratic Republic of Ethiopia", "ET"),
            ("ʾĪtyōṗṗyā", "ET"),
            ("የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ", "ET"),
            ("Republic of Tajikistan", "TJ"),
            ("TJ", "TJ"),
            ("Tajikistan", "TJ"),
            ("Toçikiston", "TJ"),
            ("Çumhuriyi Toçikiston", "TJ"),
            ("Ҷумҳурии Тоҷикистон", "TJ"),
            ("BA", "BA"),
            ("Bosnia and Herzegovina", "BA"),
            ("Bosnia-Herzegovina", "BA"),
            ("Босна и Херцеговина", "BA"),
            ("BL", "BL"),
            ("Collectivity of Saint Barthélemy", "BL"),
            ("Collectivité de Saint-Barthélemy", "BL"),
            ("Saint Barthélemy", "BL"),
            ("St. Barthelemy", "BL"),
            ("CN", "CN"),
            ("China", "CN"),
            ("People's Republic of China", "CN"),
            ("Zhongguo", "CN"),
            ("Zhonghua", "CN"),
            ("Zhōngguó", "CN"),
            ("Zhōnghuá Rénmín Gònghéguó", "CN"),
            ("中华人民共和国", "CN"),
            ("Beluu er a Belau", "PW"),
            ("PW", "PW"),
            ("Palau", "PW"),
            ("Republic of Palau", "PW"),
        ])
    });

pub fn find(name: &str) -> Option<&'static str> {
    COUNTRIES.get(name).cloned()
}
